version: "3"
services:
  vote:
    image: voting-app
    ports:
      - "5000:80"
  redis:
    image: redis:alpine
  worker:
    image: worker-app
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  result:
    image: result-app
    ports:
      - "5001:80"